---
image: docker:latest

services:
  - docker:dind

variables:
  ANSIBLE_LINT: "quay.io/samsung_cnct/ansible-lint:latest"

stages:
  - stage-1
  - stage-2

job-1:
  stage: stage-1
  image: $ANSIBLE_LINT
  script:
    - hack/wait2

job-2:
  stage: stage-1
  image: $ANSIBLE_LINT
  artifacts:
    paths:
      - $CI_PROJECT_DIR/demo/hi
  script:
    - hack/wait

job-3:
  stage: stage-2
  image: $ANSIBLE_LINT
  script:
    - cat $CI_PROJECT_DIR/demo/hi
