---
- name: Flannel provider
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.fabric/kraken.fabric.flannel'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster.fabricConfig.provider == 'flannel'

- name: Calico provider
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.fabric/kraken.fabric.calico'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster.fabricConfig.provider == 'calico'

- name: Error Fabric Provider
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.error'
    kraken_component_type: fabric
    kraken_component_error: 'Unsupported provider'
    kraken_component_name: '{{ cluster.fabricConfig.provider }}'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: cluster_node_tuple
  when: "cluster.fabricConfig.provider not in ['flannel', 'calico']"