---
# The cluster UUID can not be used twice, even if cluster formation fails midway.
# Since templates are unconditionally generated, we know terraform will be forced
# to regenerate the instance, or fail on up, since prevent_destroy will be set
# for the terraform resource.
#
# Cf. https://coreos.com/etcd/docs/latest/v2/discovery_protocol.html and
# https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md
- name: Generate cluster UUID
  command: >
    uuidgen
  register: uuidgen_result
  when:
    - etcd.uuidToken is defined
    - etcd.uuidToken

- debug:
    var: uuidgen_result
    verbosity: 0
  when:
    - etcd.uuidToken is defined
    - etcd.uuidToken

- name: Fail if uuidgen failed
  fail:
    msg: "uuidgen failed with {{ uuidgen_result.stderr }}"
  when:
    - etcd.uuidToken is defined
    - etcd.uuidToken
    - uuidgen_result | failed

- set_fact:
    clusterUuidToken: "{{ uuidgen_result.stdout | lower }}"
  when:
    - etcd.uuidToken is defined
    - etcd.uuidToken

- debug:
    msg: >
      The UUID for (cluster, nodePool) ({{ cluster_node_tuple.0.name }},
      {{ etcd.name }}) is {{ clusterUuidToken }}
    verbosity: 0
  when:
    - etcd.uuidToken is defined
    - etcd.uuidToken

- name: Generate etcd .units.etcd.part files
  template: src=etcd.units.etcd.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster_node_tuple.0.name }}/{{ cluster_node_tuple.1.name }}.units.kraken-etcd-{{ etcd.name }}.part"

- name: Generate kraken-ssl .units.etcd.part files
  template: src=etcd.units.kraken-etcd-ssl.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster_node_tuple.0.name }}/{{ cluster_node_tuple.1.name }}.units.kraken-etcd-ssl-{{ etcd.name }}.part"
