 - include: deploy-canal.yaml
   with_subelements:
     - "{{ kraken_config.clusters }}"
     - nodePools
   loop_control:
     loop_var: cluster_node_tuple
   when: cluster_node_tuple.1.apiServerConfig is defined